name: EvenMoreFish
author: Oheers
version: 1.4.0.14
main: com.oheers.fish.EvenMoreFish
api-version: 1.16
depend: [Vault]
softdepend: [WorldGuard, PlaceholderAPI, RedProtect, mcMMO]
loadbefore: [AntiAC]

commands:
  evenmorefish:
    usage: /<command> [name]
    aliases: [emf]





#  There are roughly 300-400 moose roaming freely in the woods of Sweden